<a href="https://colab.research.google.com/github/AnaNum10/2025_2/blob/main/PA_LU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# seccion para importar cuadernillos en colab desde github
!pip install import-ipynb
!wget https://raw.githubusercontent.com/AnaNum10/2025_2/main/LU.ipynb
import import_ipynb
from LU import SolverLU

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 24.8 MB/s eta 0:00:00
--2025-03-25 22:21:25--  https://raw.githubusercontent.com/AnaNum10/2025_2/main/LU.ipynb
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7803 (7.6K) [text/plain]
Saving to: ‘LU.ipynb’

LU.ipynb            100%[===================>]   7.62K  --.-KB/s    in 0s      

2025-03-25 22:21:25 (81.6 MB/s) - ‘LU.ipynb’ saved [7803/7803]



In [2]:
import numpy as np
from numpy import linalg as LA

A=np.array([[2.0,1.0,1.0],[4.0,-6.0,0.0],[-2.0,7.0,2.0]])
b=np.array([1.,2.,3.])
A

array([[ 2.,  1.,  1.],
       [ 4., -6.,  0.],
       [-2.,  7.,  2.]])

In [2]:
A[[1,0]]=A[[0,1]]
A

array([[ 4., -6.,  0.],
       [ 2.,  1.,  1.],
       [-2.,  7.,  2.]])

In [11]:
j=1
k=np.argmax(np.abs(A[j:,j]))+j
k

np.int64(2)

In [3]:
def Permutaciones(A,b):
  U=np.copy(A)
  x=np.copy(b)
  P=np.eye(A.shape[0])

  for j in range(A.shape[0]):
    k=np.argmax(np.abs(A[j:,j]))+j
    U[[j,k]]=U[[k,j]]
    P[[j,k]]=P[[k,j]]
    x[[j,k]]=x[[k,j]]

  return P,U,x

In [14]:
P,U,x=Permutaciones(A,b)
U

array([[ 4., -6.,  0.],
       [-2.,  7.,  2.],
       [ 2.,  1.,  1.]])

In [4]:
def Solver_LU_Pivot_Partial(A,b):
    P,Ap,bp=Permutaciones(A,b)
    x=SolverLU(Ap,bp)

    return x

In [5]:
SOl=Solver_LU_Pivot_Partial(A,b)
print("La solucion es: ",SOl)
print("La solucion analítica es: ",LA.solve(A,b))

La solucion es:  [-1. -1.  4.]
La solucion analítica es:  [-1. -1.  4.]
