<a href="https://colab.research.google.com/github/AnaNum10/2025_2/blob/main/ResolucionDeSistemas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import numpy as np
from numpy import linalg as LA

Sistema diagonal

In [37]:
import numpy as np

def SolverDiagonal(A, b):
    """
    Resuelve un sistema de ecuaciones lineales donde la matriz A es diagonal.

    Esta función resuelve el sistema de ecuaciones Ax = b, donde A es una matriz diagonal
    representada por su diagonal principal (un vector). La solución se obtiene dividiendo
    cada elemento del vector b por el correspondiente elemento de la diagonal de A.

    Parámetros:
    -----------
    A : array_like
        Un arreglo unidimensional que representa la diagonal principal de la matriz A.
        Debe tener la misma longitud que el vector b.

    b : array_like
        Un arreglo unidimensional que representa el vector de términos independientes del sistema.

    Retorna:
    --------
    x : ndarray
        Un arreglo unidimensional que contiene la solución del sistema Ax = b.

    Ejemplo:
    --------
    >>> A = np.array([2, 4, 6])  # Diagonal principal de la matriz A
    >>> b = np.array([8, 16, 36])  # Vector de términos independientes
    >>> x = SolverDiagonal(A, b)
    >>> print(x)
    [4. 4. 6.]

    Notas:
    ------
    - La función asume que la matriz A es diagonal y que no hay elementos fuera de la diagonal.
    - Si algún elemento de la diagonal A es cero, se producirá un error de división por cero.
    """
    n = len(A)
    x = np.zeros_like(A, dtype=float)  # Asegura que x sea de tipo flotante
    for i in range(n):
        x[i] = b[i] / A[i]
    return x

In [38]:
AA=np.array([1.0,2.0,3.0])
bb=np.ones_like(AA)

SolverDiagonal(AA,bb)

array([1.        , 0.5       , 0.33333333])

In [43]:
def SustitucionDelante(Mat,b):
  n=Mat.shape[0]
  x=np.zeros(n)

  x[0]=b[0]/Mat[0,0]
  for i in range(n):
    SumCum=0.0
    print("i=",i)
    for j in range(i-1):
      print("j=",j)
      SumCum+=Mat[j,i]*x[j]
    x[i]=(b[i]-SumCum)/Mat[i,i]

  return x

In [44]:
import numpy as np

# Crear una matriz cuadrada de ejemplo
matriz = np.array([[1.0, 2.0, 3.0],
                   [4.0, 5.0, 6.0],
                   [7.0, 8.0, 9.0]])

# Convertir la matriz en una matriz triangular inferior
MTI = np.tril(matriz)
print(MTI)

[[1. 0. 0.]
 [4. 5. 0.]
 [7. 8. 9.]]


In [45]:
SustitucionDelante(MTI,bb)

i= 0
i= 1
i= 2
j= 0


array([1.        , 0.2       , 0.11111111])

In [42]:
LA.solve(MTI,bb)

array([ 1.        , -0.6       , -0.13333333])